/**
 * 
 */
package standup.connector;

/**
 * A Connector Exception.
 * All custom exceptions generated by this API will throw exceptions
 * derived from this type.
 */
public class ConnectorException extends Exception {

	private static final long serialVersionUID = 1L;

	public ConnectorException(String message) {
		super(message);
	}

	public ConnectorException(String message, Throwable cause) {
		super(message, cause);
	}

}
